# Generated by Django 5.2.5 on 2025-08-31 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da Categoria')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('icone', models.CharField(choices=[('heart', 'Coração'), ('star', 'Estrela'), ('leaf', 'Folha'), ('sun', 'Sol'), ('moon', 'Lua'), ('flower', 'Flor'), ('butterfly', 'Borboleta'), ('rainbow', 'Arco-íris'), ('peace', 'Paz'), ('smile', 'Sorriso')], default='heart', max_length=20, verbose_name='Ícone')),
                ('cor', models.CharField(choices=[('#11B5A4', 'Verde Principal'), ('#4F9785', 'Verde Escuro'), ('#89D4CE', 'Verde Claro'), ('#FFB74D', 'Laranja'), ('#64B5F6', 'Azul'), ('#BA68C8', 'Roxo'), ('#FF8A65', 'Coral'), ('#A5D6A7', 'Verde Suave'), ('#FFCC80', 'Amarelo Suave'), ('#F8BBD9', 'Rosa')], default='#11B5A4', max_length=7, verbose_name='Cor')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_mensagem', to='authentication.psicologo', verbose_name='Psicólogo')),
            ],
            options={
                'verbose_name': 'Categoria de Mensagem',
                'verbose_name_plural': 'Categorias de Mensagem',
                'ordering': ['nome'],
                'unique_together': {('psicologo', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='SementeCuidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('conteudo', models.TextField(verbose_name='Conteúdo da Mensagem')),
                ('tipo', models.CharField(choices=[('motivacional', 'Motivacional'), ('reflexao', 'Reflexão'), ('exercicio', 'Exercício'), ('dica', 'Dica'), ('lembrete', 'Lembrete'), ('gratidao', 'Gratidão'), ('mindfulness', 'Mindfulness'), ('autoestima', 'Autoestima'), ('respiracao', 'Respiração'), ('meditacao', 'Meditação')], default='motivacional', max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('ativa', 'Ativa'), ('programada', 'Programada'), ('pausada', 'Pausada'), ('arquivada', 'Arquivada')], default='ativa', max_length=20, verbose_name='Status')),
                ('publica', models.BooleanField(default=False, help_text='Se marcado, todos os pacientes receberão esta mensagem', verbose_name='Mensagem Pública')),
                ('data_programada', models.DateTimeField(blank=True, null=True, verbose_name='Data Programada para Envio')),
                ('recorrente', models.BooleanField(default=False, verbose_name='Mensagem Recorrente')),
                ('total_visualizacoes', models.PositiveIntegerField(default=0, verbose_name='Total de Visualizações')),
                ('total_curtidas', models.PositiveIntegerField(default=0, verbose_name='Total de Curtidas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens', to='core.categoriamensagem', verbose_name='Categoria')),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sementes_cuidado', to='authentication.psicologo', verbose_name='Psicólogo')),
            ],
            options={
                'verbose_name': 'Semente do Cuidado',
                'verbose_name_plural': 'Sementes do Cuidado',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MensagemPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enviada', 'Enviada'), ('visualizada', 'Visualizada'), ('curtida', 'Curtida'), ('arquivada', 'Arquivada')], default='enviada', max_length=20, verbose_name='Status')),
                ('enviada_em', models.DateTimeField(auto_now_add=True)),
                ('visualizada_em', models.DateTimeField(blank=True, null=True, verbose_name='Visualizada em')),
                ('curtida_em', models.DateTimeField(blank=True, null=True, verbose_name='Curtida em')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Feedback do Paciente')),
                ('avaliacao', models.PositiveSmallIntegerField(blank=True, help_text='Avaliação de 1 a 5 estrelas', null=True, verbose_name='Avaliação (1-5)')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_recebidas', to='authentication.paciente', verbose_name='Paciente')),
                ('semente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='core.sementecuidado', verbose_name='Semente do Cuidado')),
            ],
            options={
                'verbose_name': 'Mensagem do Paciente',
                'verbose_name_plural': 'Mensagens dos Pacientes',
                'ordering': ['-enviada_em'],
            },
        ),
        migrations.AddIndex(
            model_name='sementecuidado',
            index=models.Index(fields=['status'], name='core_sement_status_fc96dc_idx'),
        ),
        migrations.AddIndex(
            model_name='sementecuidado',
            index=models.Index(fields=['tipo'], name='core_sement_tipo_8dce35_idx'),
        ),
        migrations.AddIndex(
            model_name='sementecuidado',
            index=models.Index(fields=['data_programada'], name='core_sement_data_pr_192a8d_idx'),
        ),
        migrations.AddIndex(
            model_name='mensagempaciente',
            index=models.Index(fields=['status'], name='core_mensag_status_2acd9b_idx'),
        ),
        migrations.AddIndex(
            model_name='mensagempaciente',
            index=models.Index(fields=['enviada_em'], name='core_mensag_enviada_74db1b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mensagempaciente',
            unique_together={('semente', 'paciente')},
        ),
    ]
