# Generated by Django 5.2.5 on 2025-09-01 01:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('core', '0003_categoriaodisseia_metaodisseia_registroodisseia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('sessao_agendada', 'Sessão Agendada'), ('sessao_cancelada', 'Sessão Cancelada'), ('sessao_lembrete', 'Lembrete de Sessão'), ('nova_semente', 'Nova Semente do Cuidado'), ('novo_registro', 'Novo Registro de Odisseia'), ('comentario_psicologo', 'Comentário do Psicólogo'), ('meta_vencendo', 'Meta Próxima do Vencimento'), ('pagamento_pendente', 'Pagamento Pendente'), ('sistema', 'Notificação do Sistema')], max_length=30, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida')),
                ('data_leitura', models.DateTimeField(blank=True, null=True, verbose_name='Data de Leitura')),
                ('link_relacionado', models.CharField(blank=True, help_text='URL ou identificador para navegar', max_length=200, null=True, verbose_name='Link Relacionado')),
                ('dados_extras', models.JSONField(blank=True, help_text='Dados adicionais em formato JSON', null=True, verbose_name='Dados Extras')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='authentication.paciente', verbose_name='Paciente')),
                ('psicologo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='authentication.psicologo', verbose_name='Psicólogo')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['paciente', 'lida'], name='core_notifi_pacient_4e8a31_idx'), models.Index(fields=['psicologo', 'lida'], name='core_notifi_psicolo_a2d5bd_idx'), models.Index(fields=['tipo', 'created_at'], name='core_notifi_tipo_9f3957_idx')],
            },
        ),
        migrations.CreateModel(
            name='VinculoPacientePsicologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('suspenso', 'Suspenso'), ('finalizado', 'Finalizado')], default='ativo', max_length=20, verbose_name='Status')),
                ('data_vinculo', models.DateTimeField(auto_now_add=True, verbose_name='Data do Vínculo')),
                ('data_inicio_tratamento', models.DateField(default=datetime.date.today, verbose_name='Data de Início do Tratamento')),
                ('data_fim_tratamento', models.DateField(blank=True, null=True, verbose_name='Data de Fim do Tratamento')),
                ('motivo_vinculo', models.CharField(blank=True, help_text='Ex: Busca via CRP, Indicação, etc.', max_length=100, null=True, verbose_name='Motivo do Vínculo')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('permite_visualizar_registros', models.BooleanField(default=True, verbose_name='Permite Visualizar Registros de Odisseia')),
                ('permite_comentarios', models.BooleanField(default=True, verbose_name='Permite Comentários do Psicólogo')),
                ('permite_metas', models.BooleanField(default=True, verbose_name='Permite Criar Metas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_psicologo', to='authentication.paciente', verbose_name='Paciente')),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_paciente', to='authentication.psicologo', verbose_name='Psicólogo')),
            ],
            options={
                'verbose_name': 'Vínculo Paciente-Psicólogo',
                'verbose_name_plural': 'Vínculos Paciente-Psicólogo',
                'ordering': ['-data_vinculo'],
                'indexes': [models.Index(fields=['status', 'data_vinculo'], name='core_vincul_status_a1041b_idx'), models.Index(fields=['paciente', 'status'], name='core_vincul_pacient_3febed_idx'), models.Index(fields=['psicologo', 'status'], name='core_vincul_psicolo_9c2bff_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'ativo')), fields=('paciente', 'psicologo'), name='unique_vinculo_ativo_paciente_psicologo')],
            },
        ),
    ]
