# Generated by Django 5.2.5 on 2026-03-26 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_prontuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessao',
            name='tipo_sessao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessoes', to='core.tiposessao', verbose_name='Tipo de Sessão'),
        ),
    ]
