# Generated by Django 5.2.5 on 2026-04-02 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_sessao_tipo_sessao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sementecuidado',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='registroodisseia',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='comentariopsicologo',
            name='psicologo',
        ),
        migrations.RemoveField(
            model_name='comentariopsicologo',
            name='registro',
        ),
        migrations.AlterUniqueTogether(
            name='mensagempaciente',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='mensagempaciente',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='mensagempaciente',
            name='semente',
        ),
        migrations.RemoveField(
            model_name='metaodisseia',
            name='paciente',
        ),
        migrations.AlterUniqueTogether(
            name='registroodisseia',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='registroodisseia',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='sementecuidado',
            name='psicologo',
        ),
        migrations.RemoveField(
            model_name='sessao',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='sessao',
            name='psicologo',
        ),
        migrations.RemoveField(
            model_name='sessao',
            name='tipo_sessao',
        ),
        migrations.AlterUniqueTogether(
            name='tiposessao',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tiposessao',
            name='psicologo',
        ),
        migrations.DeleteModel(
            name='CategoriaMensagem',
        ),
        migrations.DeleteModel(
            name='CategoriaOdisseia',
        ),
        migrations.DeleteModel(
            name='ComentarioPsicologo',
        ),
        migrations.DeleteModel(
            name='MensagemPaciente',
        ),
        migrations.DeleteModel(
            name='MetaOdisseia',
        ),
        migrations.DeleteModel(
            name='RegistroOdisseia',
        ),
        migrations.DeleteModel(
            name='SementeCuidado',
        ),
        migrations.DeleteModel(
            name='Sessao',
        ),
        migrations.DeleteModel(
            name='TipoSessao',
        ),
    ]
