# Generated by Django 5.2.5 on 2026-09-14 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_sementecuidado_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacaosistema',
            name='tipo',
            field=models.CharField(choices=[('sessao_agendada', 'Sessão Agendada'), ('sessao_cancelada', 'Sessão Cancelada'), ('sessao_lembrete', 'Lembrete de Sessão'), ('sessao_confirmacao', 'Confirmação Pós-Sessão'), ('nova_semente', 'Nova Semente do Cuidado'), ('novo_registro', 'Novo Registro de Odisseia'), ('comentario_psicologo', 'Comentário do Psicólogo'), ('meta_vencendo', 'Meta Próxima do Vencimento'), ('pagamento_pendente', 'Pagamento Pendente'), ('sistema', 'Notificação do Sistema')], max_length=30, verbose_name='Tipo'),
        ),
    ]
