# Generated by Django 5.2.5 on 2026-09-18 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_passwordresetcode'),
        ('core', '0008_alter_notificacaosistema_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='prontuario',
            name='paciente_nome_snapshot',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prontuarios', to='authentication.paciente'),
        ),
    ]
