# Generated by Django 5.2.5 on 2026-09-18 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_passwordresetcode'),
        ('core', '0012_saneamento_vinculos_ativos_duplicados'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vinculopacientepsicologo',
            name='unique_vinculo_ativo_paciente_psicologo',
        ),
        migrations.AddConstraint(
            model_name='vinculopacientepsicologo',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ativo')), fields=('paciente',), name='unique_vinculo_ativo_por_paciente'),
        ),
    ]
