# Generated by Django 5.2.5 on 2026-09-18 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_backfill_slug_e_codigo_convite'),
        ('core', '0013_constraint_um_vinculo_ativo_por_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinculopacientepsicologo',
            name='data_solicitacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Solicitação'),
        ),
        migrations.AddField(
            model_name='vinculopacientepsicologo',
            name='origem',
            field=models.CharField(choices=[('convite_link', 'Convite (link permanente)'), ('convite_codigo', 'Convite (código de uso único)'), ('crp', 'CRP')], default='crp', max_length=20, verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='vinculopacientepsicologo',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('suspenso', 'Suspenso'), ('finalizado', 'Finalizado'), ('pendente', 'Pendente'), ('recusado', 'Recusado'), ('expirado', 'Expirado')], default='ativo', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='ConviteVinculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, db_index=True, max_length=9, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField()),
                ('usado_em', models.DateTimeField(blank=True, null=True)),
                ('revogado', models.BooleanField(default=False)),
                ('apelido', models.CharField(blank=True, help_text='Anotação do psicólogo para localizar o convite na lista (ex.: "João, indicação da Dra. Marta").', max_length=100, null=True, verbose_name='Apelido')),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites_vinculo', to='authentication.psicologo', verbose_name='Psicólogo')),
                ('usado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='convites_resgatados', to='authentication.paciente', verbose_name='Usado por')),
            ],
            options={
                'verbose_name': 'Convite de Vínculo',
                'verbose_name_plural': 'Convites de Vínculo',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['psicologo', 'revogado', 'usado_em'], name='core_convit_psicolo_90420d_idx')],
            },
        ),
    ]
