# Generated by Django 5.2.5 on 2026-04-02 21:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_alter_psicologo_crp'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Tipo de Sessão')),
                ('tipo', models.CharField(choices=[('primeira', 'Primeira Sessão'), ('urgencia', 'Urgência'), ('avulsa', 'Avulsa'), ('presencial', 'Presencial'), ('pacote', 'Pacote'), ('online', 'Online'), ('retorno', 'Retorno')], default='avulsa', max_length=20, verbose_name='Categoria')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor (R$)')),
                ('duracao_minutos', models.PositiveIntegerField(default=50, verbose_name='Duração em Minutos')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_sessao', to='authentication.psicologo', verbose_name='Psicólogo')),
            ],
            options={
                'verbose_name': 'Tipo de Sessão',
                'verbose_name_plural': 'Tipos de Sessão',
                'ordering': ['nome'],
                'unique_together': {('psicologo', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(verbose_name='Data e Hora')),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('confirmada', 'Confirmada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada'), ('faltou', 'Paciente Faltou'), ('remarcada', 'Remarcada')], default='agendada', max_length=20, verbose_name='Status')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor (R$)')),
                ('status_pagamento', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('atrasado', 'Atrasado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status do Pagamento')),
                ('data_pagamento', models.DateTimeField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('observacoes_agendamento', models.TextField(blank=True, null=True, verbose_name='Observações do Agendamento')),
                ('observacoes_sessao', models.TextField(blank=True, null=True, verbose_name='Observações da Sessão')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='authentication.paciente', verbose_name='Paciente')),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='authentication.psicologo', verbose_name='Psicólogo')),
                ('tipo_sessao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessoes', to='sessoes.tiposessao', verbose_name='Tipo de Sessão')),
            ],
            options={
                'verbose_name': 'Sessão',
                'verbose_name_plural': 'Sessões',
                'ordering': ['-data_hora'],
                'indexes': [models.Index(fields=['data_hora'], name='sessoes_ses_data_ho_2076c2_idx'), models.Index(fields=['status'], name='sessoes_ses_status_8ffda6_idx'), models.Index(fields=['status_pagamento'], name='sessoes_ses_status__9d1645_idx')],
            },
        ),
    ]
