# Generated by Django 5.2.5 on 2026-07-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessoes', '0002_normalizar_modalidades_legadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiposessao',
            name='tipo',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('online', 'Online')], default='online', max_length=20, verbose_name='Categoria'),
        ),
    ]
