# Generated by Django 5.2.5 on 2026-09-14 23:04

import uuid

from django.db import migrations, models
from django.utils import timezone


def backfill_sala_uuid_sessoes_online_futuras(apps, schema_editor):
    """
    Gera sala_uuid para sessões online futuras que já existiam antes desta
    migration, para que a feature nasça útil sem exigir remarcação manual.
    Idempotente: só toca sessões com sala_uuid ainda nulo.
    """
    Sessao = apps.get_model('sessoes', 'Sessao')

    existentes = set(
        Sessao.objects.exclude(sala_uuid__isnull=True).values_list('sala_uuid', flat=True)
    )

    qs = Sessao.objects.filter(
        tipo_sessao__tipo='online',
        status__in=['agendada', 'confirmada', 'remarcada'],
        data_hora__gte=timezone.now(),
        sala_uuid__isnull=True,
    )
    for sessao in qs.iterator():
        novo = uuid.uuid4()
        while novo in existentes:
            novo = uuid.uuid4()
        existentes.add(novo)
        sessao.sala_uuid = novo
        sessao.save(update_fields=['sala_uuid'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('sessoes', '0003_alter_tiposessao_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessao',
            name='sala_uuid',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True, verbose_name='Identificador da Sala Online'),
        ),
        migrations.RunPython(backfill_sala_uuid_sessoes_online_futuras, noop_reverse),
    ]
