# Generated by Django 5.2.5 on 2026-09-17 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessoes', '0004_sala_uuid_sessoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessao',
            name='sala_uuid',
        ),
    ]
