# Generated by Django 5.2.5 on 2026-09-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessoes', '0005_remove_sessao_sala_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessao',
            name='cancelado_por',
            field=models.CharField(blank=True, choices=[('paciente', 'Paciente'), ('psicologo', 'Psicólogo')], max_length=10, null=True, verbose_name='Cancelado por'),
        ),
        migrations.AddField(
            model_name='sessao',
            name='cancelamento_tardio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessao',
            name='motivo_cancelamento',
            field=models.TextField(blank=True, null=True),
        ),
    ]
