# Generated by Django 5.2.5 on 2026-03-28 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psicologo',
            name='crp',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
