# Generated by Django 5.2.5 on 2026-09-17 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customuser_google_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='psicologo',
            name='link_sala_video',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Link da Sala de Vídeo (Google Meet)'),
        ),
    ]
