# Generated by Django 5.2.5 on 2026-09-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='psicologo',
            name='codigo_convite',
            field=models.CharField(blank=True, db_index=True, max_length=9, null=True, unique=True, verbose_name='Código de Convite Permanente'),
        ),
        migrations.AddField(
            model_name='psicologo',
            name='slug',
            field=models.SlugField(blank=True, max_length=160, null=True, unique=True, verbose_name='Slug (convite permanente)'),
        ),
        migrations.AddField(
            model_name='psicologo',
            name='verificacao_fonte',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('cnp', 'Consulta ao CNP'), ('provedor', 'Provedor pago')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='psicologo',
            name='verificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='psicologo',
            name='verificado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
