# Generated by Django 5.2.5 on 2026-04-02 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_remove_sementecuidado_categoria_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoPush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('expo', 'Expo'), ('fcm', 'FCM'), ('apns', 'APNs')], default='expo', max_length=20)),
                ('push_token', models.CharField(max_length=255)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], max_length=20)),
                ('app_version', models.CharField(blank=True, default='', max_length=50)),
                ('device_id', models.CharField(max_length=100)),
                ('timezone', models.CharField(blank=True, default='', max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('permissao_status', models.CharField(choices=[('granted', 'Granted'), ('denied', 'Denied'), ('undetermined', 'Undetermined')], default='undetermined', max_length=20)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos_push', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EntregaPush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('expo', 'Expo'), ('fcm', 'FCM'), ('apns', 'APNs')], default='expo', max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('receipt_ok', 'Receipt OK'), ('receipt_error', 'Receipt Error'), ('failed', 'Failed'), ('device_unregistered', 'Device Unregistered')], default='queued', max_length=30)),
                ('titulo', models.CharField(max_length=100)),
                ('mensagem', models.TextField()),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('provider_ticket_id', models.CharField(blank=True, default='', max_length=255)),
                ('provider_receipt_id', models.CharField(blank=True, default='', max_length=255)),
                ('provider_error_code', models.CharField(blank=True, default='', max_length=100)),
                ('provider_error_detail', models.TextField(blank=True, default='')),
                ('tentativas', models.PositiveIntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('receipt_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destinatario_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dispositivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notificacoes_push.dispositivopush')),
                ('notificacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.notificacaosistema')),
            ],
        ),
        migrations.AddIndex(
            model_name='dispositivopush',
            index=models.Index(fields=['user', 'ativo'], name='notificacoe_user_id_b77e2b_idx'),
        ),
        migrations.AddIndex(
            model_name='dispositivopush',
            index=models.Index(fields=['push_token', 'provider'], name='notificacoe_push_to_50b018_idx'),
        ),
        migrations.AddIndex(
            model_name='dispositivopush',
            index=models.Index(fields=['last_seen_at'], name='notificacoe_last_se_6b07bd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dispositivopush',
            unique_together={('user', 'device_id', 'provider')},
        ),
        migrations.AddIndex(
            model_name='entregapush',
            index=models.Index(fields=['status', 'next_retry_at'], name='notificacoe_status_b831ae_idx'),
        ),
        migrations.AddIndex(
            model_name='entregapush',
            index=models.Index(fields=['destinatario_user', 'created_at'], name='notificacoe_destina_47546e_idx'),
        ),
        migrations.AddIndex(
            model_name='entregapush',
            index=models.Index(fields=['provider_ticket_id'], name='notificacoe_provide_0be616_idx'),
        ),
    ]
