# Generated by Django 5.2.5 on 2026-04-02 21:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_alter_psicologo_crp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaOdisseia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da Categoria')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('icone', models.CharField(choices=[('happy', 'Feliz'), ('sad', 'Triste'), ('angry', 'Bravo'), ('anxious', 'Ansioso'), ('calm', 'Calmo'), ('excited', 'Animado'), ('confused', 'Confuso'), ('grateful', 'Grato'), ('hopeful', 'Esperançoso'), ('frustrated', 'Frustrado')], default='happy', max_length=20, verbose_name='Ícone')),
                ('cor', models.CharField(choices=[('#FFD700', 'Dourado - Alegria'), ('#FF6B6B', 'Vermelho - Raiva'), ('#4ECDC4', 'Azul Claro - Calma'), ('#45B7D1', 'Azul - Tristeza'), ('#96CEB4', 'Verde - Esperança'), ('#FFEAA7', 'Amarelo - Ansiedade'), ('#DDA0DD', 'Roxo - Reflexão'), ('#F0A3FF', 'Rosa - Amor'), ('#FFA07A', 'Salmão - Gratidão'), ('#98D8C8', 'Verde Água - Paz')], default='#FFD700', max_length=7, verbose_name='Cor')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria de Odisseia',
                'verbose_name_plural': 'Categorias de Odisseia',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome da Categoria')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('icone', models.CharField(choices=[('heart', 'Coração'), ('star', 'Estrela'), ('leaf', 'Folha'), ('sun', 'Sol'), ('moon', 'Lua'), ('flower', 'Flor'), ('butterfly', 'Borboleta'), ('rainbow', 'Arco-íris'), ('peace', 'Paz'), ('smile', 'Sorriso')], default='heart', max_length=20, verbose_name='Ícone')),
                ('cor', models.CharField(choices=[('#11B5A4', 'Verde Principal'), ('#4F9785', 'Verde Escuro'), ('#89D4CE', 'Verde Claro'), ('#FFB74D', 'Laranja'), ('#64B5F6', 'Azul'), ('#BA68C8', 'Roxo'), ('#FF8A65', 'Coral'), ('#A5D6A7', 'Verde Suave'), ('#FFCC80', 'Amarelo Suave'), ('#F8BBD9', 'Rosa')], default='#11B5A4', max_length=7, verbose_name='Cor')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_mensagem', to='authentication.psicologo', verbose_name='Psicólogo')),
            ],
            options={
                'verbose_name': 'Categoria de Mensagem',
                'verbose_name_plural': 'Categorias de Mensagem',
                'ordering': ['nome'],
                'unique_together': {('psicologo', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='MetaOdisseia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título da Meta')),
                ('descricao', models.TextField(verbose_name='Descrição da Meta')),
                ('status', models.CharField(choices=[('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('pausada', 'Pausada'), ('cancelada', 'Cancelada')], default='em_andamento', max_length=20, verbose_name='Status')),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('data_prevista', models.DateField(verbose_name='Data Prevista para Conclusão')),
                ('data_conclusao', models.DateField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('progresso', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Progresso (%)')),
                ('observacoes_progresso', models.TextField(blank=True, null=True, verbose_name='Observações sobre o Progresso')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metas_odisseia', to='authentication.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Meta de Odisseia',
                'verbose_name_plural': 'Metas de Odisseia',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='RegistroOdisseia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateField(verbose_name='Data do Registro')),
                ('hora_registro', models.TimeField(verbose_name='Hora do Registro')),
                ('situacao', models.TextField(help_text='Descreva o que estava acontecendo', verbose_name='Situação')),
                ('local', models.CharField(blank=True, help_text='Onde você estava?', max_length=100, null=True, verbose_name='Local')),
                ('humor_geral', models.CharField(choices=[('muito_triste', 'Muito Triste 😢'), ('triste', 'Triste 😔'), ('neutro', 'Neutro 😐'), ('feliz', 'Feliz 🙂'), ('muito_feliz', 'Muito Feliz 😄')], default='neutro', max_length=20, verbose_name='Humor Geral')),
                ('intensidade_emocao', models.PositiveSmallIntegerField(choices=[(1, 'Muito Baixa'), (2, 'Baixa'), (3, 'Moderada'), (4, 'Alta'), (5, 'Muito Alta')], default=3, verbose_name='Intensidade da Emoção')),
                ('pensamentos', models.TextField(help_text='O que passou pela sua cabeça?', verbose_name='Pensamentos')),
                ('pensamentos_automaticos', models.TextField(blank=True, help_text='Pensamentos que surgiram automaticamente', null=True, verbose_name='Pensamentos Automáticos')),
                ('reacoes_fisicas', models.TextField(blank=True, help_text='Como seu corpo reagiu? (tensão, respiração, etc.)', null=True, verbose_name='Reações Físicas')),
                ('comportamento', models.TextField(blank=True, help_text='Como você agiu nesta situação?', null=True, verbose_name='Comportamento')),
                ('gatilhos', models.TextField(blank=True, help_text='O que pode ter desencadeado essas emoções?', null=True, verbose_name='Gatilhos Identificados')),
                ('estrategias_enfrentamento', models.TextField(blank=True, help_text='O que você fez para lidar com a situação?', null=True, verbose_name='Estratégias de Enfrentamento')),
                ('aprendizados', models.TextField(blank=True, help_text='O que você aprendeu com esta experiência?', null=True, verbose_name='Aprendizados')),
                ('nivel_ansiedade', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Nível de Ansiedade (0-10)')),
                ('nivel_estresse', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Nível de Estresse (0-10)')),
                ('nivel_energia', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Nível de Energia (0-10)')),
                ('observacoes_adicionais', models.TextField(blank=True, null=True, verbose_name='Observações Adicionais')),
                ('compartilhar_psicologo', models.BooleanField(default=True, help_text='Permitir que o psicólogo veja este registro', verbose_name='Compartilhar com Psicólogo')),
                ('privado', models.BooleanField(default=False, help_text='Registro apenas para reflexão pessoal', verbose_name='Registro Privado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros', to='engajamentos.categoriaodisseia', verbose_name='Categoria')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_odisseia', to='authentication.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Registro de Odisseia',
                'verbose_name_plural': 'Registros de Odisseia',
                'ordering': ['-data_registro', '-hora_registro'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioPsicologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(verbose_name='Comentário')),
                ('tipo_comentario', models.CharField(choices=[('observacao', 'Observação'), ('orientacao', 'Orientação'), ('reflexao', 'Reflexão'), ('elogio', 'Elogio'), ('sugestao', 'Sugestão')], default='observacao', max_length=20, verbose_name='Tipo de Comentário')),
                ('importante', models.BooleanField(default=False, verbose_name='Comentário Importante')),
                ('lido_paciente', models.BooleanField(default=False, verbose_name='Lido pelo Paciente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_registros', to='authentication.psicologo', verbose_name='Psicólogo')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_psicologo', to='engajamentos.registroodisseia', verbose_name='Registro')),
            ],
            options={
                'verbose_name': 'Comentário do Psicólogo',
                'verbose_name_plural': 'Comentários do Psicólogo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SementeCuidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('conteudo', models.TextField(verbose_name='Conteúdo da Mensagem')),
                ('tipo', models.CharField(choices=[('motivacional', 'Motivacional'), ('reflexao', 'Reflexão'), ('exercicio', 'Exercício'), ('dica', 'Dica'), ('lembrete', 'Lembrete'), ('gratidao', 'Gratidão'), ('mindfulness', 'Mindfulness'), ('autoestima', 'Autoestima'), ('respiracao', 'Respiração'), ('meditacao', 'Meditação')], default='motivacional', max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('ativa', 'Ativa'), ('programada', 'Programada'), ('pausada', 'Pausada'), ('arquivada', 'Arquivada')], default='ativa', max_length=20, verbose_name='Status')),
                ('publica', models.BooleanField(default=False, help_text='Se marcado, todos os pacientes receberão esta mensagem', verbose_name='Mensagem Pública')),
                ('data_programada', models.DateTimeField(blank=True, null=True, verbose_name='Data Programada para Envio')),
                ('recorrente', models.BooleanField(default=False, verbose_name='Mensagem Recorrente')),
                ('total_visualizacoes', models.PositiveIntegerField(default=0, verbose_name='Total de Visualizações')),
                ('total_curtidas', models.PositiveIntegerField(default=0, verbose_name='Total de Curtidas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens', to='engajamentos.categoriamensagem', verbose_name='Categoria')),
                ('psicologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sementes_cuidado', to='authentication.psicologo', verbose_name='Psicólogo')),
            ],
            options={
                'verbose_name': 'Semente do Cuidado',
                'verbose_name_plural': 'Sementes do Cuidado',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MensagemPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enviada', 'Enviada'), ('visualizada', 'Visualizada'), ('curtida', 'Curtida'), ('arquivada', 'Arquivada')], default='enviada', max_length=20, verbose_name='Status')),
                ('enviada_em', models.DateTimeField(auto_now_add=True)),
                ('visualizada_em', models.DateTimeField(blank=True, null=True, verbose_name='Visualizada em')),
                ('curtida_em', models.DateTimeField(blank=True, null=True, verbose_name='Curtida em')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='Feedback do Paciente')),
                ('avaliacao', models.PositiveSmallIntegerField(blank=True, help_text='Avaliação de 1 a 5 estrelas', null=True, verbose_name='Avaliação (1-5)')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_recebidas', to='authentication.paciente', verbose_name='Paciente')),
                ('semente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='engajamentos.sementecuidado', verbose_name='Semente do Cuidado')),
            ],
            options={
                'verbose_name': 'Mensagem do Paciente',
                'verbose_name_plural': 'Mensagens dos Pacientes',
                'ordering': ['-enviada_em'],
            },
        ),
        migrations.AddIndex(
            model_name='registroodisseia',
            index=models.Index(fields=['data_registro'], name='engajamento_data_re_397457_idx'),
        ),
        migrations.AddIndex(
            model_name='registroodisseia',
            index=models.Index(fields=['humor_geral'], name='engajamento_humor_g_951d51_idx'),
        ),
        migrations.AddIndex(
            model_name='registroodisseia',
            index=models.Index(fields=['intensidade_emocao'], name='engajamento_intensi_96fba4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='registroodisseia',
            unique_together={('paciente', 'data_registro', 'hora_registro')},
        ),
        migrations.AddIndex(
            model_name='sementecuidado',
            index=models.Index(fields=['status'], name='engajamento_status_90ad6f_idx'),
        ),
        migrations.AddIndex(
            model_name='sementecuidado',
            index=models.Index(fields=['tipo'], name='engajamento_tipo_29be9a_idx'),
        ),
        migrations.AddIndex(
            model_name='sementecuidado',
            index=models.Index(fields=['data_programada'], name='engajamento_data_pr_d621ec_idx'),
        ),
        migrations.AddIndex(
            model_name='mensagempaciente',
            index=models.Index(fields=['status'], name='engajamento_status_b56301_idx'),
        ),
        migrations.AddIndex(
            model_name='mensagempaciente',
            index=models.Index(fields=['enviada_em'], name='engajamento_enviada_0a7a08_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mensagempaciente',
            unique_together={('semente', 'paciente')},
        ),
    ]
